/**
 * Created by jige on 2018/3/13.
 */
export const SIGNIN_USER = 'SIGNIN_USER';
export const REMEMBER_USER = 'REMEMBER_USER';

export const SET_PAGE_NO_USER_MANAGE = 'SET_PAGE_NO_USER_MANAGE';
export const SET_PAGE_SIZE_USER_MANAGE = 'SET_PAGE_SIZE_USER_MANAGE';
export const SET_PAGE_TOTAL_USER_MANAGE = 'SET_PAGE_TOTAL_USER_MANAGE';
export const SET_USER_LIST_USER_MANAGE = 'SET_USER_LIST_USER_MANAGE';